master:
  jobs:
    kuber: |-
      <?xml version='1.1' encoding='UTF-8'?>
      <jenkins.branch.OrganizationFolder plugin="branch-api@2.5.5">
        <actions/>
        <description></description>
        <displayName>kuber</displayName>
        <properties>
          <jenkins.branch.OrganizationChildHealthMetricsProperty>
            <templates>
              <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.11">
                <nonRecursive>false</nonRecursive>
              </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
            </templates>
          </jenkins.branch.OrganizationChildHealthMetricsProperty>
          <jenkins.branch.OrganizationChildOrphanedItemsProperty>
            <strategy class="jenkins.branch.OrganizationChildOrphanedItemsProperty$Inherit"/>
          </jenkins.branch.OrganizationChildOrphanedItemsProperty>
          <jenkins.branch.OrganizationChildTriggersProperty>
            <templates>
              <com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger plugin="cloudbees-folder@6.11">
                <spec>H H/4 * * *</spec>
                <interval>86400000</interval>
              </com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger>
            </templates>
          </jenkins.branch.OrganizationChildTriggersProperty>
          <org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty plugin="kubernetes@1.23.1">
            <permittedClouds/>
          </org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty>
          <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.5.0">
            <dockerLabel></dockerLabel>
            <registry plugin="docker-commons@1.16"/>
          </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
          <jenkins.branch.NoTriggerOrganizationFolderProperty>
            <branches>.*</branches>
          </jenkins.branch.NoTriggerOrganizationFolderProperty>
        </properties>
        <folderViews class="jenkins.branch.OrganizationFolderViewHolder">
          <owner reference="../.."/>
        </folderViews>
        <healthMetrics>
          <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.11">
            <nonRecursive>false</nonRecursive>
          </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
        </healthMetrics>
        <icon class="jenkins.branch.MetadataActionFolderIcon">
          <owner class="jenkins.branch.OrganizationFolder" reference="../.."/>
        </icon>
        <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.11">
          <pruneDeadBranches>true</pruneDeadBranches>
          <daysToKeep>-1</daysToKeep>
          <numToKeep>-1</numToKeep>
        </orphanedItemStrategy>
        <triggers>
          <com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger plugin="cloudbees-folder@6.11">
            <spec>H H/4 * * *</spec>
            <interval>86400000</interval>
          </com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger>
        </triggers>
        <disabled>false</disabled>
        <navigators>
          <org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator plugin="github-branch-source@2.5.8">
            <repoOwner>t0ster</repoOwner>
            <credentialsId>github</credentialsId>
            <traits>
              <jenkins.scm.impl.trait.WildcardSCMSourceFilterTrait plugin="scm-api@2.6.3">
                <includes>kuber*</includes>
                <excludes></excludes>
              </jenkins.scm.impl.trait.WildcardSCMSourceFilterTrait>
              <org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
                <strategyId>1</strategyId>
              </org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
              <org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
                <strategyId>2</strategyId>
              </org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
            </traits>
          </org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator>
        </navigators>
        <projectFactories>
          <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory plugin="workflow-multibranch@2.21">
            <scriptPath>Jenkinsfile</scriptPath>
          </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory>
        </projectFactories>
        <buildStrategies/>
      </jenkins.branch.OrganizationFolder>
