---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "kuber-stack.labels" . | nindent 4 }}
    app: mongodb
spec:
  # replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kuber-stack.selectorLabels" . | nindent 6 }}
      app: mongodb
  template:
    metadata:
      labels:
        {{- include "kuber-stack.selectorLabels" . | nindent 8 }}
        app: mongodb
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: mongodb
          # image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: mongo
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "kuber-stack.labels" . | nindent 4 }}
    app: mongodb
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    {{- include "kuber-stack.selectorLabels" . | nindent 4 }}
    app: mongodb
---
