---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "kuber-stack.labels" . | nindent 4 }}
    app: ui
spec:
  # replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kuber-stack.selectorLabels" . | nindent 6 }}
      app: ui
  template:
    metadata:
      labels:
        {{- include "kuber-stack.selectorLabels" . | nindent 8 }}
        app: ui
      annotations:
        release: "{{ .Values.release }}"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: REACT_APP_HOST
              value: {{ .Values.host }}
            - name: REACT_APP_PARSE_URL
              value: "http://{{ .Values.host }}/parse"
          # command: ["/bin/sh"]
          # args: ["-c", "tail -f /dev/null"]
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "kuber-stack.labels" . | nindent 4 }}
    app: ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    {{- include "kuber-stack.selectorLabels" . | nindent 4 }}
    app: ui
---
